#!/bin/bash

# Fix Xcode Project Duplicate Files Issue
# This script helps clean up the project file to remove duplicate references

echo "🔧 Fixing Xcode Project Duplicate Files Issue"
echo "============================================="

echo ""
echo "❌ Issue: Multiple commands produce the same output files"
echo "This happens when files are referenced multiple times in the Xcode project."
echo ""
echo "📋 Manual Fix Required in Xcode:"
echo "================================="
echo ""
echo "1. Open SampleApp.xcodeproj in Xcode"
echo ""
echo "2. Clean Up Duplicate References:"
echo "   - Select the SampleApp target"
echo "   - Go to 'Build Phases' tab"
echo "   - Expand 'Compile Sources'"
echo "   - Look for duplicate entries (same file listed multiple times)"
echo "   - Remove any duplicate entries by clicking the '-' button"
echo ""
echo "3. Check WhiteLabel Target:"
echo "   - Select the WhiteLabel target"
echo "   - Go to 'Build Phases' tab"
echo "   - Expand 'Compile Sources'"
echo "   - Make sure each Swift file appears only ONCE"
echo "   - Remove any duplicates"
echo ""
echo "4. Alternative: Remove and Re-add Files:"
echo "   - Right-click on WhiteLabel target"
echo "   - Choose 'Add Files to WhiteLabel'"
echo "   - Navigate to WhiteLabel/WhiteLabel/ directory"
echo "   - Select all .swift files"
echo "   - Make sure 'Add to target: WhiteLabel' is checked"
echo "   - Click 'Add'"
echo ""
echo "5. Clean and Build:"
echo "   - Product → Clean Build Folder"
echo "   - Product → Build"
echo ""
echo "🎯 Expected Result:"
echo "=================="
echo "Build should succeed without duplicate file errors."
echo ""
echo "✨ After fixing, run the app to see the Sentry bundle exclusion logs!"
